config/routes.rb
Nomster::Application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'places#index'

  resources :places do
    resources :comments, :only => :create
    resources :photos, :only => :create
  end 

  resources :users, :only => :show

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :place
  after_create :send_comment_email

  RATINGS = {
    'one star'    => '1_star',
    'two stars'   => '2_stars',
    'three stars' => '3_stars',
    'four stars'  => '4_stars',
    'five stars'  => '5_stars'
  }

  def humanized_rating
    RATINGS.invert[self.rating]
  end

  def send_comment_email
      NotificationMailer.comment_added(self).deliver
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :place
	mount_uploader :picture, PictureUploader
end

app/models/place.rb
class Place < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy
	has_many :photos

	geocoded_by :address
  	after_validation :geocode

	validates :name, :presence => true, :length => { :minimum => 4 }
	validates :address, :presence => true
	validates :description, :presence => true

	def self.search(search)
	  # where("name ILIKE ?", "%#{search}%") 
	  # where("description ILIKE ?", "%#{search}%")
	  where("(name ILIKE ?) OR (description ILIKE ?)", "%#{search}%", "%#{search}%")

	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :places 
  has_many :comments  
  
  validates :user_name, :presence => true, :length => { :minimum => 4 }    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	def create
		@place = Place.find(params[:place_id])
		@place.comments.create(comment_params.merge(:user => current_user))
		update_average_rating
		redirect_to place_path(@place)

	end
	
	def update_average_rating
		integer_rating = {
		    '1_star' => 1.0,
		    '2_stars' => 2.0,
		    '3_stars' => 3.0,
		    '4_stars' => 4.0,
		    '5_stars' => 5.0
		}

		place_comments = @place.comments
	    sum = 0
	    place_comments.each do |comment|
	    	sum += integer_rating[comment.rating]
	    end
	    avg = (sum / place_comments.length).to_f

	    @place.update_attributes(average_rate: avg)
    end	

	private

	  def comment_params
	    params.require(:comment).permit(:message, :rating)
	  end	
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!
  def create
  	@place = Place.find(params[:place_id])
  	@place.photos.create(photo_params)
  	redirect_to place_path(@place)
  end

  private

  def photo_params
    params.require(:photo).permit(:picture, :caption)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]

	def index

        # if params[:search]
        # 	@places = Place.search(params[:search]).order("created_at DESC")
        # else	
			
			# Param received from sort method
        	sort_method = params[:sort_by] 

	        if sort_method.present?
			  if sort_method == 'name'
			  	sort_str = 'name ASC'
			  elsif sort_method == 'rating'
			  	sort_str = 'average_rate DESC'
			  elsif sort_method == 'date'
			  	sort_str = 'created_at ASC'
			  end
			else
				sort_str = 'created_at ASC'
	        end

			@places = Place.search(params[:search]).paginate(:page => params[:page], :per_page => 4).order(sort_str)
		# end	 
	end	

	def new
		@place = Place.new
	end

	def create
		@place = current_user.places.create(place_params)
  		if @place.valid?
    		redirect_to root_path
 		else
    		render :new, :status => :unprocessable_entity
  		end
	end	

	def show
		@place = Place.find(params[:id])
		@comment = Comment.new
		@photo = Photo.new
	end	

	def edit
		 @place = Place.find(params[:id])

		 if @place.user != current_user
    		return render :text => 'Not Allowed', :status => :forbidden
  		 end
	end	

	def update
		@place = Place.find(params[:id])
		 if @place.user != current_user
    		return render :text => 'Not Allowed', :status => :forbidden
  		 end

		@place.update_attributes(place_params)
		if @place.valid?
		  redirect_to root_path
		else
		  render :edit, :status => :unprocessable_entity
		end
	end	

	def destroy
		@place = Place.find(params[:id])
		if @place.user != current_user
    		return render :text => 'Not Allowed', :status => :forbidden
  		end
  		@place.destroy
  		redirect_to root_path
	end	

	private

	def place_params
    	params.require(:place).permit(:name, :description, :address)
  	end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  private

  def sign_up_params
    params.require(:user).permit(:user_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:user_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		#@user = User.find(params[:id])
		@user = User.where(:id => params[:id]).first
		if @user.blank?
      		render :text => "404 Not Found", :status => :not_found
    	end
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">  
  <title>Nomster</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
	<nav class="navbar" role="navigation">
  	<div class="container-fluid">
    	<!-- Brand and toggle get grouped for better mobile display -->
    	<div class="navbar-header">
      	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        	<span class="sr-only">Toggle navigation</span>
        	<span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <%= link_to 'Veggie Restaurants in MA', root_path(:sort_by => 'date'), :class => 'navbar-brand' %>
	    </div>

    	<!-- Collect the nav links, forms, and other content for toggling -->
    	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <!-- <ul class="nav navbar-nav">
	        <li>
      			<%= link_to new_place_path, :class => 'new-place' do %>
    				<i class="glyphicon glyphicon-plus-sign"></i>
    				Add a restaurant
  				<% end %>

    		</li>
	      </ul> -->
	      <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li><%= link_to 'My Profile', user_path(current_user) %></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
          <% end %>
	        
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>

  
    <% if notice.present? %>
      <div class="row">
        <p class="alert alert-success text-center"><%= notice %></p>
      </div> 
    <% end %>
    <% if alert.present? %>
      <!-- <p class="alert alert-success"><%= alert %></p> -->
      <div class="row">
        <p class="alert alert-success text-center">Please sign in or sign up to continue.</p>
      </div>  
    <% end %>

  <div class="container">

    <%= yield %>
  </div>  
</body>
</html>

app/views/places/edit.html.erb
<div class="row">
 <div class="booyah-box top-page-margin">
  <h1>Edit the restaurant's info</h1>
  <br/>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <br/>
    <%= f.input :address %>
    <br/>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Update', :class => 'btn btn-success' %>
  <% end %>
 </div>
</div> 

app/views/places/index.html.erb
<!-- <div class="container">  -->
 
<div class="row"> 
    <div class="browse-title col-xs-12"> Browse through the restaurant listings or add another</div>
</div>

 <div class="row title-row">
     <div class="title-button">
      <%= link_to new_place_path, :class => 'btn btn-success col-xs-6 col-sm-3' do %>
        Add a restaurant
      <% end %> 
     </div> 
 
      <!-- Sort functionality -->
      <!-- <div class="dropdown col-xs-2 title-button col-xs-6 col-sm-3">
        <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Sort by &nbsp;
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <li>
            <%= link_to root_path(:sort_by => 'name') do %>
            Name
            <% end %>
          </li>  
          <li>
            <%= link_to root_path(:sort_by => 'rating') do %>
              Rating
            <% end %>
          </li>
          <li>
            <%= link_to root_path(:sort_by => 'date') do %>
            Date Added
            <% end %>
          </li>
        </ul>
      </div> -->

<!--       <div class="pull-right col-xs-6 col-sm-5 col-sm-offset-4">
 -->
      <div class="pull-right">



        <div class="digg_pagination">
          <%= will_paginate @places, :container => false %>
        </div>
      </div> 
</div> 

<div class="row">
<!--  <div class="col-lg-6"> -->

<!-- Sort functionality -->
      <div class="dropdown title-button">
        <button class="btn btn-success col-xs-6 col-sm-2 col-sm-offset-4 dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Sort by &nbsp;
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <li>
            <%= link_to root_path(:sort_by => 'name') do %>
            Name
            <% end %>
          </li>  
          <li>
            <%= link_to root_path(:sort_by => 'rating') do %>
              Rating
            <% end %>
          </li>
          <li>
            <%= link_to root_path(:sort_by => 'date') do %>
            Date Added
            <% end %>
          </li>
        </ul>
      </div>  

  <div class="input-group">
   <div class="col-xs-6 col-sm-6 col-lg-6">
    <%= form_tag(root_path, :method => "get", id: "search-form") do %>
     <span class="input-group-btn">
        <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search for..." %>
      
        <%= button_tag "Go!", type: "submit", class: "btn btn-success" %>
      </span> 
    <% end %>
  </div>
 </div>
</div>  

<% if !@places.present? %>
    <br /><br />
    <p>There are no places containing the term <%= params[:search] %>.</p>
<% end %>




<!-- <div id="carousel-example-generic" class="carousel slide" data-ride="carousel"> -->
  <!-- Indicators -->
  <!-- <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol> -->

  <!-- Wrapper for slides -->
  <!-- <div class="carousel-inner"> -->
   <!--  <div class="item active">
      <%= image_tag 'slider5.jpg', :class => 'img-responsive' %>
      <div class="carousel-caption col-sm-4">
        The best vegetarian places in Massachusetts
      </div>
    </div>
    <div class="item">
    <%= image_tag 'slider9.jpg', :class => 'img-responsive' %>
    <div class="carousel-caption col-sm-4">
      There are many
    </div>
  </div>
  <div class="item">
    <%= image_tag 'slider10.jpg', :class => 'img-responsive' %>
    <div class="carousel-caption col-sm-4">
      Here is another one
    </div>
  </div>
 -->
 <!--  </div> -->

  <!-- Controls -->
  <!-- <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div> -->

<div class="clear"></div>
<% @places.each do |place| %>
<div class="clear"></div>

<div class="row">
 <div class="booyah-box col-xs-12">

  <div class="col-xs-12 col-sm-6">
	  <h1><%= link_to place.name, place_path(place) %></h1><br />
		<i><%= place.address %></i><br /><br />
		<p><%= place.description %></p><br />
		<% if place.user.present? %>
      <small > <%= place.user.user_name %></small>
	  <% end %>
   </div>

	    <% if place.photos.present? %>
       <!-- <div class="row"> -->
	    	<!-- <div class="col-xs-12 col-sm-4"> -->
        <div class="col-xs-12 col-sm-4 col-sm-offset-2">
	  			<div class="booyah-box">
	  	  			<%= image_tag place.photos.last.picture, :class => 'img-responsive img-rounded' %>
	  	  			<div class="clear"></div>
	  	  			<br/>	
	      			<b><%= place.photos.last.caption %></b>  
	  			</div>
			  </div>
       <!-- </div>  -->
	    <% end %>
	  


    <% if place.comments.present? %>
	    <div class="col-xs-12">
		    <blockquote>
		      <% if place.comments.last.humanized_rating.present? %>
		        <b><%= place.comments.last.humanized_rating %></b> -
		      <% end %>
		      <%= place.comments.last.message %>
		      <small><%= place.comments.last.user.user_name %></small>
		    </blockquote>
	  	</div>
	  <% end %>
    <br/>

    <div class="col-xs-12 dark-greenc">
      <% if place.average_rate > 0 %>
         Average rating: 
         <%= place.average_rate.round(3) %>	
          stars
      <% end %>   
    </div>
  </div>
 </div>
<% end %>

<!-- </div>

app/views/places/new.html.erb
<div class="row">
 <div class="booyah-box top-page-margin">
	<h1>Tell us about the restaurant</h1>
	<br/>
	<%= simple_form_for @place do |f| %>
    	<%= f.input :name %>
    	<br/>
    	<%= f.input :address %>
    	<br/>
    	<%= f.input :description %>
    	<br/>
    	<%= f.submit 'Create', :class => 'btn btn-success' %>
  	<% end %>
  </div>  
</div>	

app/views/places/show.html.erb

<div class="row">
  <%= link_to new_place_path, :class => 'btn btn-success add-restaurant' do %>
    Add a restaurant
  <% end %>
</div>  

<div class="row">
 <div class="booyah-box col-xs-12">	
	<h1 class="text-green"><%=  @place.name %></h1>
  <br/>
	<i><%= @place.address %></i>
	<br/><br/>
	<p><%= @place.description %></p>

   <% if @place.latitude.present? && @place.longitude.present? %>   
    <script>

	function initMap() {
	  	var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};

	  	var map = new google.maps.Map(document.getElementById('map'), {
	    	zoom: 12,
	    	center: myLatLng
	  	});

	  	var marker = new google.maps.Marker({
	    	position: myLatLng,
	    	map: map,
	    	title: 'Hello World!'
	  	});
	}

    </script>
    <script async defer
        src="https://maps.googleapis.com/maps/api/js?signed_in=true&callback=initMap"></script>

    <div id="map"></div> 
   <% end %>
   
   <br />    



	<div class="pull-right">
		<% if current_user && current_user == @place.user %>
			<button class="btn btn-success" data-toggle="modal" data-target="#myModal">
			  Add a photo
			</button>
    		<%= link_to 'Edit', edit_place_path(@place), :class => 'btn btn-success' %>
    		<%= link_to 'Delete', place_path(@place), :method => :delete, :data => {:confirm => 'Are you sure you want to delete this?'},:class => 'btn btn-danger' %>
    	<% end %>	
    
  </div>
 </div>	
</div>

<div class="clear"></div>
<!-- Modal for photos-->
<!--the form-->

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add a photo</h4>
      </div>

      <%= simple_form_for @photo, :url => place_photos_path(@place) do |f| %>
        <div class="modal-body">
          <%= f.input :picture %>
          <br/>
          <%= f.input :caption %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit "Add a Photo", :class => 'btn btn-success' %>
        </div>
      <% end %>

    </div>
  </div>
</div>
 

<!--showing the photos/captions-->
<!-- <div class="col-xs-10 col-xs-offset-1">
	<h1 class="pull-left">Photos</h1>

	<% if current_user && current_user == @place.user %>
		<button class="btn btn-primary btn-lg pull-right" data-toggle="modal" data-target="#myModal">
		  Add a photo
		</button>
	<% end %>	
</div> -->

<div class="clear"></div>
<!-- <div class="row">
 <% @place.photos.each do |photo| %>

 <div class="col-xs-12 col-sm-4"> -->
  <!-- <div class="booyah-box"> -->
  <!-- <div class="panel panel-default">
    <div class="panel-body">
  	  	<%= image_tag photo.picture, :class => 'img-responsive img-rounded img-cen' %>
  	  <div class="clear"></div>
  	  <br/>	
      <b><i><%= photo.caption %></i></b> 
    </div>   
  </div>
 </div>
 <% end %> 
</div> -->

<div class="row">

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <!-- <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol> -->

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <% @place.photos.each_with_index do |photo, i| %>
      <% if i == 0 %>
        <% class_str = "item active" %>
      <% else %>
        <% class_str = "item" %>
      <% end %>  
      <div class="<%= class_str %>" >
        <%= image_tag photo.picture, :class => 'img-responsive' %>
        <div class="carousel-caption col-sm-4">
          <%= photo.caption %>
        </div>
      </div>
    <% end %>  
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>
</div>


<div class="clear"></div>

<!-- Modal for comments-->
<div class="modal fade" id="myModal_2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add a comment</h4>
      </div>

      <%= simple_form_for @comment, :url => place_comments_path(@place) do |f| %>
        <div class="modal-body">
          <%= f.input :message %>
          <br/>
          <%= f.input :rating, :as => :select, :collection => Comment::RATINGS %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit "Add a Comment", :class => 'btn btn-success' %>
        </div>
      <% end %>

    </div>
  </div>
</div>

<br/>
<br/>

<div class="row">
 <div class="col-xs-12">
  <% if @place.comments.present? %>
	  <h2 class="pull-left dark-green">Comments</h1>
  <% else %>
    <h4 class="pull-left dark-green comment-title-padding">No comments yet. Be the first to write one.</h4>
  <% end %>  
  
	<!-- Button trigger modal -->
  <!-- <button class="btn btn-primary btn-lg pull-right" data-toggle="modal" data-target=" -->
	<button class="btn btn-success pull-right" data-toggle="modal" data-target="#myModal_2">
	  Add a comment
	</button>
 </div> 
</div>

</br>
<div class="clear"></div>

<div class="row">
<div class="col-xs-12 dark-green">
      <% if @place.average_rate > 0 %>
         Average rating: 
         <%= @place.average_rate.round(3) %>
          stars
      <% end %>   
</div>  
<% @place.comments.each do |comment| %>
 
  <div class="col-xs-12 col-sm-6">
    <blockquote>
      <% if comment.humanized_rating.present? %>
        <b><%= comment.humanized_rating %></b> -
      <% end %>
      <%= comment.message %>
      <small><%= comment.user.user_name %></small>
    </blockquote>
  </div>
 
<% end %> 
</div> 


app/views/users/show.html.erb
<div class="row">
  <%= link_to new_place_path, :class => 'btn btn-success add-restaurant' do %>
    Add a restaurant
  <% end %>
</div> 

<div class="row">
<div class="booyah-box">
	<div class="col-xs-12 col-xs-offset-2 col-sm-4 col-sm-offset-0">
    <h4 class="text-green">My user name: <%= @user.user_name %></h4>
		<div class="col-xs-offset-1 col-sm-offset-1">
			<%= image_tag 'user.png' %>
		</div>	

		<h4 class="text-green"><%= @user.email %></h4>
		<br/>
	</div>
	
	<div class="col-xs-12 col-xs-offset-0 col-sm-5 col-sm-offset-1">
		
		<h4 class="text-center">Member Since: <%= @user.created_at.strftime("%B %d, %Y") %></h4>
		<hr>
		<h5 class="text-center"><%= @user.comments.count %> total comments</h5>
		<br/>
		<h5 class="text-center"><%= @user.comments.where(:rating => '5_stars').count %>  Five-Star Raitings</h5>
	</div>
	<div class="clear"></div>	
</div>
</div>	
<div class="clear"></div>

<br /><br />
<div class="row">
<h2 class="text-center dark-green">My Comments</h2>
<br /><br />
<% @user.comments.each do |comment| %>
  <div class="col-xs-12 col-sm-6">
    <h3 class="text-center"><%= link_to comment.place.name, place_path(comment.place) %></h3>
    <blockquote>
      <% if comment.humanized_rating.present? %>
        <b><%= comment.humanized_rating %></b> -
      <% end %>
      <%= comment.message %>
      <small><%= comment.user.user_name %></small>
    </blockquote>
  </div>
<% end %>
</div>

<div class="clear"></div>
<br /><br />

<div class="row">
  <h2 class="text-center dark-green">My Places</h2>
</div>  
<br /><br />

 
<% @user.places.each do |place| %>
 <div class="row">
  <div class="booyah-box col-xs-12">

    <div class="col-xs-12 col-sm-6">
      <h1><%= link_to place.name, place_path(place) %></h1><br />
      <i><%= place.address %></i><br /><br />
      <p><%= place.description %></p><br />
    </div>

    <% if place.photos.present? %>
        <div class="col-xs-12 col-sm-4 col-sm-offset-2">
          <div class="booyah-box">
              <%= image_tag place.photos.last.picture, :class => 'img-responsive img-rounded' %>
              <div class="clear"></div>
              <br/> 
              <b><%= place.photos.last.caption %></b>  
          </div>
        </div>
      <% end %>
   
    <% if place.comments.present? %>
      <div class="col-xs-12">
        <blockquote>
          <% if place.comments.last.humanized_rating.present? %>
            <b><%= place.comments.last.humanized_rating %></b> -
          <% end %>
          <%= place.comments.last.message %>
          <small><%= place.comments.last.user.user_name %></small>
        </blockquote>
      </div>
    <% end %>

    <div class="col-xs-12 dark-green">
      <% if place.average_rate > 0 %>
         Average rating: 
         <%= place.average_rate.round(3) %>
          stars
      <% end %>   
    </div>  

  </div>
 </div> 
<% end %>
